In [1]:
 import numpy as np

## Data types and attributes

In [2]:
# numpy's main datatype is n-d array

a1 = np.array([[1,3.1,5], [3.5, 9.9, 7]])
a2 = np.array([[[5,9,3], [6,8.3,2.8], [5,9,2], [4,8,6.6]]])


In [3]:
a1

array([[1. , 3.1, 5. ],
       [3.5, 9.9, 7. ]])

In [4]:
a2

array([[[5. , 9. , 3. ],
        [6. , 8.3, 2.8],
        [5. , 9. , 2. ],
        [4. , 8. , 6.6]]])

In [5]:
a2.shape

(1, 4, 3)

In [6]:
a1.ndim, a2.ndim
#dimensions

(2, 3)

In [8]:
a1.dtype, a2.dtype

(dtype('float64'), dtype('float64'))

In [9]:
a1.size, a2.size

(6, 12)

In [10]:
type(a1)

numpy.ndarray

In [11]:
#craete a dataframe from numpy arrays

import pandas as pd

df = pd.DataFrame(a1)
a1

array([[1. , 3.1, 5. ],
       [3.5, 9.9, 7. ]])

## Creating numpy arrays

In [12]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [16]:
random_array = np.random.randint(0, 10, size=(3,5))

In [17]:
random_array

array([[9, 1, 0, 9, 7],
       [7, 3, 2, 7, 0],
       [8, 1, 0, 6, 2]])

In [24]:
np.random.seed(7)
rand_array = np.random.random((5,3))


In [27]:
rand_array

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [28]:
np.unique(rand_array)

array([0.06593635, 0.07205113, 0.07630829, 0.26843898, 0.2881456 ,
       0.38094113, 0.43840923, 0.4998825 , 0.50112046, 0.53849587,
       0.67923   , 0.72346518, 0.77991879, 0.80373904, 0.97798951])

In [29]:
a1

array([[1. , 3.1, 5. ],
       [3.5, 9.9, 7. ]])

In [30]:
a2

array([[[5. , 9. , 3. ],
        [6. , 8.3, 2.8],
        [5. , 9. , 2. ],
        [4. , 8. , 6.6]]])

In [31]:
a1[0]

array([1. , 3.1, 5. ])

In [32]:
a1.shape

(2, 3)

In [34]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [35]:
#get the first 4 numbers of the innermost array

a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

In [36]:
a1

array([[1. , 3.1, 5. ],
       [3.5, 9.9, 7. ]])

In [37]:
a2

array([[[5. , 9. , 3. ],
        [6. , 8.3, 2.8],
        [5. , 9. , 2. ],
        [4. , 8. , 6.6]]])

In [38]:
# How can you make a1 compatible to a2?

a1 * a2

ValueError: operands could not be broadcast together with shapes (2,3) (1,4,3) 

In [39]:
a1 + ones

array([[ 2. ,  4.1,  6. ],
       [ 4.5, 10.9,  8. ]])

In [40]:
a1 / ones

array([[1. , 3.1, 5. ],
       [3.5, 9.9, 7. ]])

In [41]:
a1 ** a1

array([[1.00000000e+00, 3.33596320e+01, 3.12500000e+03],
       [8.02117802e+01, 7.19098572e+09, 8.23543000e+05]])

In [42]:
np.square(a2)

array([[[25.  , 81.  ,  9.  ],
        [36.  , 68.89,  7.84],
        [25.  , 81.  ,  4.  ],
        [16.  , 64.  , 43.56]]])

In [43]:
np.exp(a1)

array([[2.71828183e+00, 2.21979513e+01, 1.48413159e+02],
       [3.31154520e+01, 1.99303704e+04, 1.09663316e+03]])

In [44]:
np.log(a1)

array([[0.        , 1.13140211, 1.60943791],
       [1.25276297, 2.29253476, 1.94591015]])

## Aggregation

In [45]:
# performing the same operations on a number of things

In [46]:
# use python methods on python data types and use numpy's methods on numpy's arrays

In [47]:
massive_array = np.random.random(10000)
massive_array.size

10000

In [48]:
massive_array[:100]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015,
       0.85697563, 0.0336742 , 0.5326448 , 0.79695136, 0.97513968,
       0.27425859, 0.16910106, 0.87670093, 0.90918246, 0.19753289,
       0.44152974, 0.71923214, 0.84534516, 0.16827531, 0.66496896,
       0.80783546, 0.54971412, 0.16471666, 0.0355288 , 0.28153382,
       0.80787085, 0.04476626, 0.00821651, 0.36161665, 0.06362229,
       0.1494863 , 0.02319037, 0.52471984, 0.6966959 , 0.42705349,
       0.13457046, 0.33135721, 0.59034585, 0.94066139, 0.99255772,
       0.24160292, 0.01057991, 0.83064033, 0.92661294, 0.45860348,
       0.77144234, 0.86619903, 0.6096148 , 0.87262718, 0.02390303,
       0.27159522, 0.27721958, 0.12063243, 0.91071345, 0.03043927,
       0.67256103, 0.07133969, 0.36078049, 0.41809954, 0.18140429,
       0.5210141 , 0.53499176, 0.31704388, 0.73708806, 0.16020241,
       0.19250822, 0.35451102, 0.37837613, 0.20628586, 0.91870

In [49]:
%timeit sum(massive_array)  #python sum
%timeit np.sum(massive_array)   #numpy sum

955 µs ± 23.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
6.27 µs ± 90.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [50]:
#here we can see numpy's method is faster on numpy array

In [52]:
np.mean(a1)

4.916666666666667

In [53]:
np.var(a1)   #variance

8.304722222222223

In [54]:
np.std(a1)   #standard deviation

2.8817914952720334

## Reshape and transpose arrays

In [56]:
a1*a2

ValueError: operands could not be broadcast together with shapes (2,3) (1,4,3) 

In [59]:
a1.shape

(2, 3)

In [61]:
a2.shape

(1, 4, 3)

In [70]:
a1_re = a1.reshape(2,3,1)

In [71]:
a1_re

array([[[1. ],
        [3.1],
        [5. ]],

       [[3.5],
        [9.9],
        [7. ]]])

In [72]:
a1_re.shape

(2, 3, 1)

In [73]:
a1_re * a2

ValueError: operands could not be broadcast together with shapes (2,3,1) (1,4,3) 

In [77]:
# Transpose - flips the axes

In [78]:
a1.T

array([[1. , 3.5],
       [3.1, 9.9],
       [5. , 7. ]])

In [79]:
a1.T.shape

(3, 2)

## Dot Product

In [81]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))

In [82]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [83]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [84]:
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [85]:
mat2.T

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [86]:
mat2.T.shape

(3, 5)

In [87]:
np.dot(mat1, mat2.T)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

## Comparison operators

In [88]:
a1

array([[1. , 3.1, 5. ],
       [3.5, 9.9, 7. ]])

In [96]:
a3 = np.array([3, 5, 7])

In [97]:
a3

array([3, 5, 7])

In [98]:
a1 > a3

array([[False, False, False],
       [ True,  True, False]])

In [99]:
a1 >= a3

array([[False, False, False],
       [ True,  True,  True]])

In [100]:
a1 == a1

array([[ True,  True,  True],
       [ True,  True,  True]])

## Sorting arrays

In [101]:
random_array

array([[9, 1, 0, 9, 7],
       [7, 3, 2, 7, 0],
       [8, 1, 0, 6, 2]])

In [102]:
random_array.shape

(3, 5)

In [103]:
np.sort(random_array)

array([[0, 1, 7, 9, 9],
       [0, 2, 3, 7, 7],
       [0, 1, 2, 6, 8]])

In [104]:
np.argsort(random_array)

array([[2, 1, 4, 0, 3],
       [4, 2, 1, 0, 3],
       [2, 1, 4, 3, 0]], dtype=int64)

In [107]:
np.argmin(random_array, axis = 0)   #columns

array([1, 0, 0, 2, 1], dtype=int64)

In [108]:
np.argmin(random_array, axis = 1)  #rows

array([2, 4, 2], dtype=int64)

In [109]:
np.argmax(random_array, axis = 0)

array([0, 1, 1, 0, 0], dtype=int64)

## Pratical Example

In [116]:
import matplotlib.pyplot as plt
import pandas as pd

## Import image in markdown format
## <img src="panda.png"/>

<img src="panda.png"/>

In [119]:
# turn image in numpy array

In [120]:
from matplotlib.image import imread

panda = imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [121]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [122]:
panda.size


24465000

In [124]:
panda.shape, panda.ndim

((2330, 3500, 3), 3)

In [126]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.